name = "MinFEM"
uuid = "bd0dc85c-d10e-11e8-1961-03914cacc29c"
authors = ["Martin Siebenborn <martin.siebenborn@uni-hamburg.de>", "Henrik Wyschka <henrik.wyschka@uni-hamburg.de>"]
version = "2.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
